language: node_js

os: linux

cache: false

jobs:
  include:
    - stage: github pages
      node_js: "10"
      script:
        - echo "Publish site to github pages ..."
        - npm install -g hexo-cli
        - hexo algolia
        - hexo g
      deploy:
        provider: pages
        token: $GITHUB_TOKEN
        keep_history: false
        local_dir: public
        skip_cleanup: true
        on:
          branch: site
