# Site
title: MYCOIN.NAME
subtitle:
description: (none)
author: mycoin
language: zh
timezone:

url: https://mycoin.name
root: /
permalink: :category/:post_title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: # Open external links in new tab
  enable: true
  field: post
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format 
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'empty'

# Pagination 
per_page: 10
pagination_dir: page

index_generator:
  per_page: 10

archive_generator:
  per_page: 20
  yearly: true
  monthly: true

category_generator:
  per_page: 10

tag_generator:
  per_page: 10

# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
## Themes: https://github.com/hexojs/hexo/wiki/Themes
theme: icarus

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/mycoin/mycoin.github.io.git
  branch: main

marked:
  gfm: false

githubEmojis:
  className: not-gallery-item

# algolia:
#   applicationID: T0CJF4ZB1O
#   apiKey: bcbeb94d417749ab5c65b082fce32333
#   indexName: hexo-icarus
